openapi: 3.0.0
info:
  title: Licensing Server
  version: 0.0.0
paths:
  /offers/{uuid}:
    summary: Returns information about a license offer.
    parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
    responses:
      200:
        content:
          application/json:
            schema:
              type: object
              properties:
                1.0.0:
                  title: Version 1 Offer
                  type: object
                  required: [url, licensor, pricing]
                  additionalProperties: true
                  properties:
                    url:
                      type: string
                      format: uri
                      pattern: ^https://
                    licensor:
                      type: string
                      format: uuid
                    pricing:
                      type: object
                      properties:
                        single:
                          $ref: https://example.com/schemas/price.json
                        site:
                          $ref: https://example.com/schemas/price.json
                      patternProperties:
                        ^\d+$:
                          $ref: https://example.com/schemas/price.json
      400:
        description: The specified UUID is not a valid UUID.
      404:
        description: An offer with the specified UUID was not found.
      default:
        description: Unexpected Error
  /order/:
    post:
      summary: Initiate an order for one or more paiod licenses.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [offers, licensee]
              properties:
                offers:
                  type: array
                  items:
                    type: string
                    format: uuid
                licensee:
                  type: object
                  required: [email, jurisdiction, name]
                  additionalProperties: true
                  properties:
                    email:
                      type: string
                      format: email
                    jurisdiction:
                      $ref: https://example.com/schemas/iso31662.json
                    name:
                      type: string
                      minLength: 3
    responses:
      303:
        description: The order is ready to complete.
        headers:
          Location:
            description: The URL for the page to complete the order.
            schema:
              type: string
              format: uri
      5XX:
        description: Unexpected Error
